apiVersion: v1
kind: Pod
metadata:
  labels:
    name: myapp
  name: myapponfailure
  namespace: teama
spec:
  containers:
  - image: psrv3/batch35dhr
    name: myappcontainer
    ports:
    - containerPort: 5000
  restartPolicy: OnFailure
