apiVersion: v1
kind: Service
metadata:
  labels:
    name: myapp
  name: myappsvc2
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: myapp
  type: LoadBalancer
