
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-task
  template:
    metadata:
      labels:
        app: flask-task
    spec:
      containers:
        - name: flask
          image: psrv3/flaskposgresqlapp
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "postgres"
            - name: FLASK_HOST
              value: "0.0.0.0"
            - name: FLASK_PORT
              value: "5000"
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-task-service
spec:
  selector:
    app: flask-task
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort
