replicaCount: 2
image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

environment: development

redis:
  enabled: false

resources: {}

redisSecret:
  enabled: true
  password: myredispassword
