apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces: ["**"]
  external_services:
    istio:
      root_namespace: istio-system
  service:
    type: NodePort
