---
- name: Create directories based on environment and app
  hosts: localhost
  become: yes
  tasks:
    - name: Create environment-app directories
      file:
        path: "/opt/{{ item.env }}/{{ item.app }}"
        state: directory
        mode: '0755'
      loop:
        - { env: "dev", app: "web" }
        - { env: "prod", app: "db" }
