---
- name: Custom failure condition with register
  hosts: localhost
  tasks:
    - name: Run command and check stderr
      command: ls /nonexistentpath
      register: ls_output
      failed_when: "'No such file or directory' not in ls_output.stderr"

    - name: Print command output
      debug:
        var: ls_output
