apiVersion: v1
kind: Pod
metadata:
  name: log-web-pod
spec:
  volumes:
  - name: log-volume
    emptyDir: {}

  containers:
  - name: app
    image: busybox
    command: [ "sh", "-c", "while true; do echo $(date) 'Hello from app' >> /usr/share/nginx/html/app.log; sleep 2; done" ]
    volumeMounts:
    - name: log-volume
      mountPath: /usr/share/nginx/html # write logs here

  - name: nginx
    image: nginx
    volumeMounts:
    - name: log-volume
      mountPath: /usr/share/nginx/html # serve logs from here
    ports:
    - containerPort: 80

#kubectl create -f example3.yaml
#kubectl port-forward pod/log-web-pod 8080:80
#http://localhost:8080/app.log
