apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {} # ephemeral storage

  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html # Nginx serves from here
    ports:
    - containerPort: 80

  - name: busybox
    image: busybox
    command: [ "sh", "-c", "echo '<h1>Hello from BusyBox!</h1>' > /data/index.html && sleep 3600" ]
    volumeMounts:
    - name: shared-data
      mountPath: /data # writes to the shared volume

#kubectl create -f example1.yaml
#kubectl port-forward pod/shared-volume-pod 8080:80
#open http://localhost:8080
