apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "while true; do echo Hello from BusyBox; sleep 5; done" ]

#kubectl create -f example.yaml
#kubectl logs multi-container-pod -c busybox
