apiVersion: v1
kind: Pod
metadata:
  name: log-html-pod
spec:
  volumes:
  - name: html-log-volume
    emptyDir: {}

  containers:
  - name: app
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "<html><body><h2>App Logs</h2>" > /usr/share/nginx/html/index.html
      while true; do
        echo "$(date) - App is running<br>" >> /usr/share/nginx/html/index.html
        sleep 2
      done
    volumeMounts:
    - name: html-log-volume
      mountPath: /usr/share/nginx/html

  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-log-volume
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80

#kubectl create -f example4.yaml
#kubectl port-forward pod/log-html-pod 8080:80
#http://localhost:8080
