
version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    image: psrv3/flaskposgresqlapp
    environment:
      DB_HOST: db
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
