{{- if and .Values.redisSecret.enabled .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: {{ .Values.redisSecret.password | b64enc }}
{{- end }}
