apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-task1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-task
  template:
    metadata:
      labels:
        app: flask-task
    spec:
      containers:
        - name: flask
          image: psrv3/flaskposgresqlapp
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: flask-config
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-task-service1
spec:
  selector:
    app: flask-task
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort
